/**
 * @appgram/react
 *
 * React library for integrating Appgram portal features
 * with pre-built UI components and headless hooks.
 */

// Provider
export {
  AppgramProvider,
  useAppgramContext,
  type AppgramProviderProps,
  type AppgramConfig,
  type AppgramContextValue,
} from './provider'

// Client
export { AppgramClient, type AppgramClientConfig } from './client'

// Hooks
export {
  useWishes,
  useWish,
  useVote,
  useComments,
  useRoadmap,
  useReleases,
  useRelease,
  useHelpCenter,
  useHelpFlow,
  useHelpArticle,
  useSupport,
  useSurvey,
  useSurveySubmit,
  useContactForm,
  useContactFormSubmit,
  // Aliases for consistency with React Native SDK
  useForm,
  useFormSubmit,
  useStatus,
  useBlogPosts,
  useBlogPost,
  useBlogCategories,
  useFeaturedPosts,
  useWaitlist,
  type UseWishesOptions,
  type UseWishesResult,
  type UseWishOptions,
  type UseWishResult,
  type UseVoteOptions,
  type UseVoteResult,
  type UseCommentsOptions,
  type UseCommentsResult,
  type UseRoadmapOptions,
  type UseRoadmapResult,
  type UseReleasesOptions,
  type UseReleasesResult,
  type UseReleaseOptions,
  type UseReleaseResult,
  type UseHelpCenterOptions,
  type UseHelpCenterResult,
  type UseHelpFlowOptions,
  type UseHelpFlowResult,
  type UseHelpArticleOptions,
  type UseHelpArticleResult,
  type UseSupportOptions,
  type UseSupportResult,
  type UseSurveyOptions,
  type UseSurveyResult,
  type UseSurveySubmitOptions,
  type UseSurveySubmitResult,
  type UseContactFormOptions,
  type UseContactFormResult,
  type UseContactFormSubmitOptions,
  type UseContactFormSubmitResult,
  // Type aliases for consistency with React Native SDK
  type UseFormOptions,
  type UseFormResult,
  type UseFormSubmitOptions,
  type UseFormSubmitResult,
  type UseStatusOptions,
  type UseStatusResult,
  type UseBlogPostsOptions,
  type UseBlogPostsResult,
  type UseBlogPostOptions,
  type UseBlogPostResult,
  type UseBlogCategoriesOptions,
  type UseBlogCategoriesResult,
  type UseFeaturedPostsOptions,
  type UseFeaturedPostsResult,
  type UseWaitlistOptions,
  type UseWaitlistResult,
} from './hooks'

// Components
export {
  VoteButton,
  WishCard,
  WishList,
  WishDetail,
  SubmitWishForm,
  RoadmapColumn,
  RoadmapBoard,
  ReleaseCard,
  ReleaseList,
  ReleaseDetail,
  Releases,
  WhatsNewPopup,
  HelpCollections,
  HelpArticles,
  HelpArticleDetail,
  HelpCenter,
  type QuickAction,
  SupportForm,
  SurveyRenderer,
  ContactFormRenderer,
  StatusBoard,
  StatusIncidentDetail,
  BlogCard,
  BlogList,
  BlogPostDetail,
  Blog,
  ChatWidget,
  type VoteButtonProps,
  type WishCardProps,
  type WishListProps,
  type WishDetailProps,
  type SubmitWishFormProps,
  type RoadmapColumnProps,
  type RoadmapBoardProps,
  type ReleaseCardProps,
  type ReleaseListProps,
  type ReleaseDetailProps,
  type ReleasesProps,
  type WhatsNewPopupProps,
  type HelpCollectionsProps,
  type HelpArticlesProps,
  type HelpArticleDetailProps,
  type HelpCenterProps,
  type SupportFormProps,
  type SurveyRendererProps,
  type ContactFormRendererProps,
  type StatusBoardProps,
  type StatusIncidentDetailProps,
  type BlogCardProps,
  type BlogListProps,
  type BlogPostDetailProps,
  type BlogProps,
  type ChatWidgetProps,
  type ChatSource,
  type StatusData,
  type StatusComponent,
  type StatusIncident,
  type IncidentUpdate,
  type OverallStatus,
  type ComponentStatus,
  type IncidentStatus,
  type IncidentImpact,
} from './components'

// Types
export type {
  // Wish types
  Wish,
  WishStatus,
  WishPriority,
  WishFilters,
  WishesResponse,
  WishAuthor,
  Category,
  // Vote types
  Vote,
  VoteCheckResponse,
  VoteCreateInput,
  VoteState,
  // Comment types
  Comment,
  CommentAuthor,
  CommentCreateInput,
  CommentsResponse,
  // Roadmap types
  Roadmap,
  RoadmapColumn as RoadmapColumnType,
  RoadmapItem,
  RoadmapData,
  RoadmapVisibility,
  // Release types
  Release,
  ReleaseFeature,
  ReleasesResponse,
  // Help types
  HelpCollection,
  HelpFlow,
  HelpArticle,
  HelpCenterData,
  HelpArticlesResponse,
  ArticleType,
  FlowDisplayType,
  // Support types
  SupportRequest,
  SupportMessage,
  SupportAttachment,
  SupportRequestInput,
  SupportRequestStatus,
  SupportRequestPriority,
  SupportRequestCategory,
  SupportRequestsResponse,
  // Survey types
  Survey,
  SurveyNode,
  SurveyNodeOption,
  SurveyNodeBranch,
  SurveyQuestionType,
  SurveyResponse,
  SurveyAnswer,
  SurveySubmitInput,
  // Contact form types
  ContactForm,
  ContactFormField,
  ContactFormFieldType,
  ContactFormFieldValidation,
  ContactFormSubmission,
  ContactFormSubmitInput,
  // Form type aliases (for consistency with React Native SDK)
  Form,
  FormField,
  FormFieldType,
  FormFieldValidation,
  FormIntegration,
  FormSubmission,
  FormSubmitInput,
  // Status API types
  StatusPage,
  StatusUpdate as StatusUpdateApi,
  StatusPageService,
  StatusPageOverview,
  StatusType,
  StatusState,
  // Customization types
  CustomColors,
  CustomTypography,
  AppgramTheme,
  ThemeMode,
  LayoutConfig,
  // Blog types
  BlogPost,
  BlogCategory,
  BlogPostsResponse,
  BlogFilters,
  // Waitlist types
  WaitlistJoinInput,
  WaitlistCount,
  WaitlistStatus,
  WaitlistEntry,
  // API types
  ApiResponse,
  PaginatedResponse,
} from './types'

// Utilities
export { cn, getFingerprint, resetFingerprint } from './utils'
